plugins {
    id 'outpost.java-conventions'
}

dependencies {
    implementation 'org.springframework:spring-context'
    implementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit-pioneer:junit-pioneer:2.3.0'
    testImplementation project(':common-iso:repository')
    testImplementation project(':payment:common:repository')
    testImplementation project(':account:repository')
    testImplementation project(':merchant-configuration:repository')
    testImplementation project(':accounting:repository')
    testImplementation project(':payment:repository')
    testImplementation project(':common-iso:domain')
    testImplementation project(':payment:common:domain')
    testImplementation project(':account:domain')
    testImplementation project(':merchant-configuration:domain')
    implementation project(':platform-sanity:static-data-repository')
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation project(path: ':platform-sanity:static-data-model')
}

tasks.named('test') {
    useJUnitPlatform()
}
