plugins {
    id 'outpost.domain-conventions'
}

group = 'com.outpost.accounting'

dependencies {
    implementation project(':platform-sanity:static-data-model')
    implementation project(':common-iso:domain')
    implementation project(':payment:common:domain')
    implementation project(':account:domain')
    implementation project(':merchant-configuration:domain')
    implementation project(':tax:domain')
    implementation project(':fx:domain')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
