plugins {
    id 'outpost.java-conventions'
}

dependencies {
    implementation project(':framework:persistence')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation project(':platform-sanity:static-data-check')
    implementation project(':accounting:persistence')
    implementation project(':accounting:domain')
    implementation project(':common-iso:domain')
    implementation project(':common-payment:domain')
    implementation project(':account:domain')
    implementation project(':merchant-configuration:domain')
    implementation project(':tax')
    implementation project(':fx')
}
