plugins {
    id 'outpost.java-conventions'
}

dependencies {
    implementation project(':common-persistence')
    implementation project(':platform-sanity:static-data-check')
    implementation project(':common-iso')
    implementation project(':common-payment')
    implementation project(':account-configuration')
    implementation project(':merchant-configuration')
    implementation project(':accounting')
    implementation project(':tax')
    implementation project(':fx')
}
