plugins {
    id 'outpost.domain-conventions'
}

dependencies {
    implementation project(':platform-sanity:static-data-model')
    implementation project(':common-iso:domain')
    implementation project(':common-payment:domain')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
