plugins {
    id 'outpost.java-conventions'
}

dependencies {
    implementation project(':framework:persistence')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation project(':platform-sanity:static-data-check')
    implementation project(':common-iso')
    implementation project(':common-payment')
    implementation project(':account-configuration')
    implementation project(':merchant-configuration')
    implementation project(':tax')
    implementation project(':payment')
    implementation project(':psp-integration')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation testFixtures(project(':framework:persistence'))
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
