plugins {
    id 'outpost.java-conventions'
    id 'java-library'
}

group = 'com.outpost.accounting'

base {
    archivesName = 'accounting-api'
}

dependencies {
    api 'org.springframework:spring-context'
    api 'org.springframework:spring-web'
    api 'com.fasterxml.jackson.core:jackson-annotations'
    api 'tools.jackson.core:jackson-databind'
    api project(':accounting:report')
    api project(':common-iso:domain')
    api project(':payment:common:domain')
    api project(':framework:logging')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
