plugins {
    id 'outpost.java-conventions'
}

group = 'com.outpost.common.iso'

base {
    archivesName = 'common-iso-repository'
}

dependencies {
    implementation project(':common-iso:domain')
    implementation project(':platform-sanity:static-data-repository')
    implementation project(':framework:persistence')
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.1.0'
}
