plugins {
    id 'outpost.java-conventions'
}

group = 'com.outpost.account.configuration'

base {
    archivesName = 'merchant-configuration-repository'
}

dependencies {
    implementation project(':merchant-configuration:domain')
    implementation project(':platform-sanity:static-data-repository')
    implementation project(':framework:persistence')
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.1.0'
    testImplementation testFixtures(project(':framework:persistence'))
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
