plugins {
    id 'outpost.java-conventions'
    id 'java-library'
}

dependencies {
    api 'org.slf4j:slf4j-api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
