plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    id 'org.springframework.boot' version '4.1.1' apply false
}

rootProject.name = 'outpost'

include(
    ':platform-sanity:static-data-model',
    ':platform-sanity:domain-architecture',
    ':platform-sanity:static-data-check',
    ':platform-sanity:static-data-repository',
    ':common-iso:repository',
    ':common-iso:domain',
    ':common-payment:repository',
    ':common-payment:domain',
    ':account:repository',
    ':account:domain',
    ':merchant-configuration:repository',
    ':merchant-configuration:domain',
    ':framework:persistence',
    ':framework:logging',
    ':framework:security',
    ':accounting:domain',
    ':accounting:persistence',
    ':tax',
    ':fx',
    ':payment:domain',
    ':psp-integration:domain',
    ':psp-integration:client',
    ':gateway-api',
    ':ledger-api',
    ':outpost-worker',
    ':static-data-job'
)
