plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'outpost'

include(
    ':platform-sanity:static-data-model',
    ':platform-sanity:static-data-check',
    ':common-iso',
    ':common-payment',
    ':account-configuration',
    ':merchant-configuration',
    ':accounting',
    ':tax',
    ':fx',
    ':payment',
    ':psp-integration',
    ':outpost-api',
    ':outpost-ledger-service',
    ':outpost-worker',
    ':seed-job'
)
