plugins {
    id 'outpost.domain-conventions'
}

dependencies {
    implementation project(':platform-sanity:static-data-model')
    implementation project(':common-iso:domain')
    implementation project(':common-payment:domain')
    implementation project(':tax')
    implementation project(':psp-integration')
}
