plugins {
    id 'outpost.java-conventions'
}

dependencies {
    implementation project(':platform-sanity:static-data-check')
    implementation project(':common-iso')
    implementation project(':account-configuration')
    implementation project(':merchant-configuration')
    implementation project(':payment')
    implementation project(':psp-integration')
}
