plugins {
    id 'outpost.java-conventions'
    id 'java-library'
}

group = 'com.outpost.accounting'

base {
    archivesName = 'accounting-api-client'
}

dependencies {
    implementation project(':accounting:api')
    api project(':framework:security')
    implementation 'org.springframework:spring-context'
    api 'org.springframework:spring-web'
}
